## Importamos las librerias necesarias

In [1]:
#Importo pandas y numpy

import numpy as np
import pandas as pd
import re

## Importamos el archivo para cargarlo en un dataframe

In [2]:
#Guardo el path del archivo en una variable para despues cargarlo en un df

file = 'C:/Users/Ramiro/Desktop/Digital House/Desafios/properatti.csv'

# Creo un DataFrame con la info del csv
df = pd.read_csv(file)

## Vemos las caracteristicas principales del df

In [ ]:
# Veo la forma del df
df.head()

In [92]:
#Veo la info del df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121220 entries, 0 to 121219
Data columns (total 24 columns):
Tipo_Operacion        121220 non-null object
Tipo_Propiedad        121220 non-null object
Barrio                121197 non-null object
Ubicacion_Completa    121220 non-null object
Pais                  121220 non-null object
Provincia             121220 non-null object
GeoNames_ID           102503 non-null float64
Latitud_Longitud      69670 non-null object
Latitud               69670 non-null float64
Longitud              69670 non-null float64
Precio                100810 non-null float64
Moneda                100809 non-null object
Precio_ARS            100810 non-null float64
Precio_Dolares        100810 non-null float64
Metros_Totales        81892 non-null float64
Metros_Cubiertos      101313 non-null float64
Precio_m2_Dls         68617 non-null float64
Precio_m2             87658 non-null float64
Pisos                 7899 non-null float64
Cantidad_Ambientes    121220 non-null object
Expensas              14262 non-null float64
Descripcion           121218 non-null object
Titulo                121220 non-null object
Amb_Desc              69657 non-null float64
dtypes: float64(13), object(11)
memory usage: 22.2+ MB

## Vemos que hay varias columnas con valores vacios

En particular vemoas que casi el 20% de las observaciones no tienen precio.

Por otro lado, vemos que, tambien alrededor del 20% de las observaciones no cuentan con el campo Superficie Cubierta en m2 y casi un 35% no cuenta con el campo Superficie Total en m2

In [85]:
# Con el metodo describe podemos ver algunos estadisticos de cada columna
df.describe()

,GeoNames_ID,Latitud,Longitud,Precio,Precio_ARS,Precio_Dolares,Metros_Totales,Metros_Cubiertos,Precio_m2,price_per_m2,Pisos,Cantidad_Ambientes,Expensas
count,1.014560e+05,68776.000000,68776.000000,1.000390e+05,1.000390e+05,1.000390e+05,81642.000000,100472.000000,68408.000000,8.696600e+04,7873.000000,46269.000000,1.426100e+04
mean,3.572585e+06,-34.644149,-59.231279,4.665494e+05,4.211908e+06,2.387094e+05,228.114880,131.580460,2162.917637,6.925705e+03,17.494983,2.904969,5.008744e+03
std,3.541295e+05,1.963298,2.264428,2.267710e+06,6.899529e+06,3.910300e+05,1654.083082,723.132808,2762.153504,2.847678e+04,120.439357,1.391094,1.204445e+05
min,3.427208e+06,-54.823985,-75.678931,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.600000,1.510204e+00,1.000000,1.000000,1.000000e+00
25%,3.430234e+06,-34.670503,-58.714033,1.100000e+05,1.582320e+06,8.967779e+04,50.000000,45.000000,1222.222222,1.555556e+03,1.000000,2.000000,1.000000e+03
50%,3.433908e+06,-34.598507,-58.479050,1.850000e+05,2.558452e+06,1.450000e+05,83.000000,74.000000,1803.702899,2.216667e+03,3.000000,3.000000,2.000000e+03
75%,3.836277e+06,-34.446362,-58.395477,4.180000e+05,4.675792e+06,2.650000e+05,200.000000,150.000000,2488.647084,3.352941e+03,6.000000,4.000000,4.000000e+03
max,6.948895e+06,4.545843,-53.733330,6.500000e+08,8.212711e+08,4.654544e+07,200000.000000,187000.000000,206333.333333,4.000000e+06,3150.000000,7.000000,1.000150e+07

Esto nos puede dar un insight de como completar los valores faltantes de las variables mas relevantes

In [71]:
# Analizo las columnas para renombrar
df.columns

Index(['Tipo_Operacion', 'Tipo_Propiedad', 'Barrio', 'Ubicacion_Completa',
       'Pais', 'Provincia', 'GeoNames_ID', 'Latitud_Longitud', 'Latitud',
       'Longitud', 'Precio', 'currency', 'Precio_ARS', 'Precio_Dolares',
       'Metros_Totales', 'Metros_Cubiertos', 'Precio_m2', 'price_per_m2',
       'Pisos', 'Cantidad_Ambientes', 'Expensas', 'Descripcion', 'Titulo'],
      dtype='object')

In [3]:
#Primero arreglo las irregularidades en las columnas
#Elimino las columnas que no aportan informacion descriptiva al df 

df = df.drop(['Unnamed: 0','image_thumbnail', 'properati_url'], axis=1)

#Renombro las columnas restantes para trabajar mas comodamente

df.rename(columns={ 'operation': 'Tipo_Operacion',
                    'property_type': 'Tipo_Propiedad',
                    'place_name': 'Barrio',
                    'place_with_parent_names': 'Ubicacion_Completa',
                    'country_name': 'Pais',
                    'state_name': 'Provincia',
                    'geonames_id': 'GeoNames_ID',
                    'lat-lon': 'Latitud_Longitud',
                    'lat': 'Latitud',
                    'lon': 'Longitud',
                    'price': 'Precio',
                    'currency': 'Moneda',
                    'price_aprox_local_currency': 'Precio_ARS',
                    'price_aprox_usd': 'Precio_Dolares',
                    'surface_total_in_m2': 'Metros_Totales',
                    'surface_covered_in_m2': 'Metros_Cubiertos',
                    'price_usd_per_m2': 'Precio_m2_Dls',
                    'price_per_m2': 'Precio_m2',
                    'floor': 'Pisos',
                    'rooms': 'Cantidad_Ambientes',
                    'expenses': 'Expensas',
                    'description': 'Descripcion',
                    'title': 'Titulo'}, inplace=True)

In [64]:
#Veamos los valores que toma el campo Cantidad Ambientes
df.Cantidad_Ambientes.value_counts()

3.0     12567
2.0     12433
4.0      7937
1.0      7377
5.0      3782
6.0      1403
7.0       770
8.0       409
10.0      226
9.0       184
11.0       72
12.0       65
13.0       33
14.0       27
15.0       26
17.0       16
16.0       11
20.0       11
22.0        8
18.0        6
21.0        5
30.0        4
25.0        4
19.0        4
32.0        3
23.0        2
24.0        1
27.0        1
29.0        1
31.0        1
28.0        1
Name: Cantidad_Ambientes, dtype: int64

## Vemos que hay muchos outliers que podrian estar mal imputados, o representar cosas como complejos de departamentos

In [74]:
df[df['Cantidad_Ambientes']> 7]

,Tipo_Operacion,Tipo_Propiedad,Barrio,Ubicacion_Completa,Pais,Provincia,GeoNames_ID,Latitud_Longitud,Latitud,Longitud,...,Precio_Dolares,Metros_Totales,Metros_Cubiertos,Precio_m2,price_per_m2,Pisos,Cantidad_Ambientes,Expensas,Descripcion,Titulo
135,sell,PH,Olivos,|Argentina|Bs.As. G.B.A. Zona Norte|Vicente Ló...,Argentina,Bs.As. G.B.A. Zona Norte,3430310.0,"-34.521608,-58.488312",-34.521608,-58.488312,...,269000.00,NaN,260.0,NaN,1034.615385,NaN,10.0,NaN,Corredor Responsable: RAUL LOPEZ - CSI 6292Con...,PH 5 DORM EXCELENTE UBICACIÓN OLIVOS QUINTA P...
177,sell,apartment,Villa Carlos Paz,|Argentina|Córdoba|Villa Carlos Paz|,Argentina,Córdoba,3832791.0,"-31.4200736,-64.4947113",-31.420074,-64.494711,...,470000.00,420.0,450.0,1119.047619,1044.444444,NaN,9.0,NaN,"CASA PRINCIPAL QUE CONSTA DE 3 DORM,.AMPLIOS,2...",SE VENDE VIVIENDA+LOCALES COMERCIALES+DPTOS
179,sell,house,Punilla,|Argentina|Córdoba|Punilla|,Argentina,Córdoba,3839996.0,"-31.389619,-64.495867",-31.389619,-64.495867,...,225000.00,NaN,250.0,NaN,900.000000,NaN,9.0,NaN,Corredor Responsable: Juan Manuel Quiroga - CP...,OPORTUNIDAD UNICA! HERMOSA CASA TOTALMENTE FINAN
180,sell,house,Emilia,|Argentina|Santa Fe|Emilia|,Argentina,Santa Fe,3856226.0,"-31.06066,-60.749647",-31.060660,-60.749647,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,Corredor Responsable: Gerardo Portmann - CCI M...,Dos propiedades en gran terreno - Emilia
295,sell,house,Santo Tomé,|Argentina|Santa Fe|Santo Tomé|,Argentina,Santa Fe,3835793.0,"-31.632885,-60.754266",-31.632885,-60.754266,...,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,Corredor Responsable: Maria Gisela Di Pangrazi...,Casa de 3 dormitorios en Altos de la Ribera
297,sell,house,Luján,|Argentina|Buenos Aires Interior|Luján|,Argentina,Buenos Aires Interior,3430982.0,"-34.5134761598,-59.1055119337",-34.513476,-59.105512,...,455000.00,NaN,290.0,NaN,1568.965517,NaN,10.0,NaN,Fracción de 5 Has-290 m2 Cubiertos-2 Casas-Pil...,Chacra en Lujan 5 Has Unica Excelente Estado
336,sell,apartment,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,"-31.3621643,-64.237574",-31.362164,-64.237574,...,NaN,420.0,NaN,NaN,NaN,NaN,8.0,NaN,"Departamento exclusivo, plano y diseño único, ...",VILLAGE PLAZA DEPARTAMENTO ÚNICO EN CERRO DE L...
676,sell,house,Luján,|Argentina|Buenos Aires Interior|Luján|,Argentina,Buenos Aires Interior,3430982.0,"-34.5957111113,-59.1328095463",-34.595711,-59.132810,...,200000.00,2800.0,190.0,71.428571,1052.631579,NaN,10.0,NaN,Casa Principal-Casa Casero-Pileta-Vestuariios-...,Casa en Venta Quinta en Hosteria Lujan
876,sell,apartment,San Nicolás,|Argentina|Capital Federal|San Nicolás|,Argentina,Capital Federal,6693229.0,"-34.605661,-58.388343",-34.605661,-58.388343,...,250000.00,NaN,382.0,NaN,654.450262,1.0,17.0,NaN,Corredor Responsable: Mario Gabriel Gerez - CU...,Venta Hotel Familiar en 2 pisos
877,sell,apartment,Monserrat,|Argentina|Capital Federal|Monserrat|,Argentina,Capital Federal,3430570.0,"-34.609988,-58.374932",-34.609988,-58.374932,...,300000.00,NaN,472.0,NaN,635.593220,1.0,22.0,NaN,Corredor Responsable: Mario Gabriel Gerez - CU...,Venta Hotel Familiar Calle Peru al 100
886,sell,house,Santa Fe,|Argentina|Santa Fe|Santa Fe|,Argentina,Santa Fe,3836277.0,"-31.605943,-60.696512",-31.605943,-60.696512,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,Corredor Responsable: Maria Gisela Di Pangrazi...,CASA EN VENTA ZONA ARISTOBULO DEL VALLE
955,sell,house,Escobar,|Argentina|Bs.As. G.B.A. Zona Norte|Escobar|,Argentina,Bs.As. G.B.A. Zona Norte,3434130.0,"-34.454973,-58.727986",-34.454973,-58.727986,...,1100000.00,NaN,20.0,NaN,55000.000000,NaN,8.0,NaN,Corredor Responsable: Raul Hector Merlo - CMCP...,Imponente Casa en 2 terrenos en Country Mirafl...
990,sell,house,Colegiales,|Argentina|Capital Federal|Colegiales|,Argentina,Capital Federal,3435356.0,"-34.5764717713,-58.4607502897",-34.576472,-58.460750,...,1550000.00,NaN,660.0,NaN,2348.484848,NaN,10.0,NaN,Corredor Responsable: Ariel Champanier - C.U.C...,Casa excelente 700m2 jardin pisc garage 4 autos
1033,sell,house,Santa Fe,|Argentina|Santa Fe|Santa Fe|,Argentina,Santa Fe,3836277.0,"-31.640325,-60.688515",-31.640325,-60.688515,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,Corredor Responsable: Caroline Hogner - CCI St...,Casa a la Venta Barrio Candioti con patio y pi...
1057,sell,house,Villa Carlos Paz,|Argentina|Córdoba|Villa Carlos Paz|,Argentina,Córdoba,3832791.0,"-31.4632866,-64.4069441",-31.463287,-64.406944,...,450000.00,2489.0,328.0,180.795500,1371.951220,NaN,10.0,NaN,"CASA CAUSANA2489 mtrs2 de terreno, 320 mtrs2 c...","V.C .PAZ, CORDOBA, HERMOSA CASA EN CAUSANA"
1064,sell,house,Villa General Belgrano,|Argentina|Córdoba|Villa General Belgrano|,Argentina,Córdoba,3832734.0,"-31.970354,-64.542833",-31.970354,-64.542833,...,NaN,NaN,174.0,NaN,NaN,NaN,8.0,NaN,"Vivienda de dos dormitorios, baño, estar comed...","Vivienda de dos dormitorios sobre Avenida, Vil..."
1435,sell,house,Claromecó,|Argentina|Buenos Aires Costa Atlántica|Clarom...,Argentina,Buenos Aires Costa Atlántica,3864887.0,"-38.8529059,-60.0840053",-38.852906,-60.084005,...,180000.00,600.0,120.0,300.000000,1500.000000,NaN,10.0,NaN,VENDEMOS dos hermosos Chalet en excelente ubic...,Dos Chalet
1536,sell,house,Santo Tomé,|Argentina|Santa Fe|Santo Tomé|,Argentina,Santa Fe,3835793.0,"-31.632591,-60.761792",-31.632591,-60.761792,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,Corredor Responsable: Caroline Hogner - CCI St...,"El Paso, excelente ubicación, casa de 3 dormit..."
1540,sell,house,Zárate,|Argentina|Buenos Aires Interior|Zárate|Zárate|,Argentina,Buenos Aires Interior,NaN,"-34.099792,-59.048274",-34.099792,-59.048274,...,60000.00,NaN,20.0,NaN,3000.000000,NaN,8.0,NaN,Corredor Responsable: Mario Gabriel Gerez - CM...,"CASA EN ZARATE, SE ACEPTAN PERMUTAS. FINANCIACION"
1597,sell,house,Villa Carlos Paz,|Argentina|Córdoba|Villa Carlos Paz|,Argentina,Córdoba,3832791.0,NaN,NaN,NaN,...,NaN,1000.0,122.0,NaN,NaN,NaN,9.0,NaN,"VENTA - Chalet con GRAN piscina, parque y exce...","** VENTA - Chalet con GRAN piscina, parque y ..."
1601,sell,house,La Granja,|Argentina|Córdoba|La Granja|,Argentina,Córdoba,3851072.0,"-31.013881,-64.268614",-31.013881,-64.268614,...,290000.00,NaN,421.0,NaN,688.836105,NaN,15.0,NaN,Corredor Responsable: Matiaz Ruiz Moreno - CPC...,Vendo Importante Casa La Granja
1796,sell,store,Palermo,|Argentina|Capital Federal|Palermo|,Argentina,Capital Federal,3430234.0,"-34.58401489,-58.4288559",-34.584015,-58.428856,...,NaN,650.0,615.0,NaN,NaN,NaN,8.0,NaN,Corredor Responsable: Federico Bogianchino Pro...,U$D 1.690.000 - Fondo de Comercio en Venta - S...
2216,sell,house,Moreno,|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|,Argentina,Bs.As. G.B.A. Zona Oeste,3430550.0,"-34.65573502,-58.77177811",-34.655735,-58.771778,...,NaN,773.0,250.0,NaN,NaN,NaN,8.0,NaN,Importante propiedad ubicada sobre Boulevard A...,U$D 240.000 - Casa en Venta - Alcorta 1400
2552,sell,house,Moreno,|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|,Argentina,Bs.As. G.B.A. Zona Oeste,3430550.0,"-34.63436508,-58.86024857",-34.634365,-58.860249,...,NaN,1100.0,300.0,NaN,NaN,NaN,8.0,NaN,chalet amplio que consta de 6 dormitorios ampl...,U$D 210.000 - Casa en Venta - Finochietto ...
2555,sell,house,Moreno,|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|,Argentina,Bs.As. G.B.A. Zona Oeste,3430550.0,"-34.63436508,-58.86024857",-34.634365,-58.860249,...,NaN,1100.0,300.0,NaN,NaN,NaN,8.0,NaN,chalet amplio que consta de 6 dormitorios ampl...,U$D 210.000 - Casa en Venta - Finochietto ...
3261,sell,house,Ituzaingó,|Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó|,Argentina,Bs.As. G.B.A. Zona Oeste,3433359.0,"-34.65927887,-58.6730423",-34.659279,-58.673042,...,NaN,NaN,200.0,NaN,NaN,NaN,9.0,NaN,Zona:Residencial-Asfalto-Obra sanitaria:Cloaca...,U$D 340.000 - Casa en Venta - Inte Carlos Ratt...
3579,sell,house,Palermo,|Argentina|Capital Federal|Palermo|,Argentina,Capital Federal,3430234.0,"-34.57114792,-58.42329788",-34.571148,-58.423298,...,NaN,800.0,800.0,NaN,NaN,NaN,8.0,NaN,"PH de estilo francés, con entrada independient...",U$D 1.380.000 - Tipo casa PH en Venta - Araoz ...
4391,sell,house,Rosario,|Argentina|Santa Fe|Rosario|,Argentina,Santa Fe,3838574.0,"-32.948117,-60.635924",-32.948117,-60.635924,...,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,Corredor Responsable: Sebastian Pellegrini - C...,Casa Zona Centro. Ideal Uso Profesional
5105,sell,house,Tandil,|Argentina|Buenos Aires Interior|Tandil|Tandil|,Argentina,Buenos Aires Interior,3427832.0,"-37.339199,-59.121914",-37.339199,-59.121914,...,980000.00,NaN,579.0,NaN,1692.573402,NaN,12.0,NaN,Corredor Responsable: Mirta Leguizamon - CMCPD...,"TANDIL, IMPORTANTE PROPIEDAD, Zona Residencial"
5131,sell,house,Pilar,|Argentina|Bs.As. G.B.A. Zona Norte|Pilar|,Argentina,Bs.As. G.B.A. Zona Norte,3429979.0,"-34.3998036665,-59.0354099748",-34.399804,-59.035410,...,230000.00,12200.0,300.0,18.852459,766.666667,NaN,10.0,NaN,"Casa Quinta-Zona Santa Coloma Pilar, Ruta 6 , ...",Casa en Venta Ruta 6 Pilar B°Santa Coloma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117080,sell,house,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,"-31.4144994,-64.1940169",-31.414499,-64.194017,...,400000.00,NaN,351.0,NaN,1139.601140,3.0,9.0,NaN,Casa en Venta de 5 dorm. en Cordoba,Corro 110 a mts de 27 de Abril Casona de
117110,sell,house,Villa General Belgrano,|Argentina|Córdoba|Villa General Belgrano|,Argentina,Córdoba,3832734.0,"-31.969544,-64.547987",-31.969544,-64.547987,...,NaN,NaN,70.0,NaN,NaN,NaN,8.0,NaN,"Vivienda de dos dormitorios, cocina, comedor, ...","Venta De Vivienda De Dos Dormitorios, Con Renta"
117123,sell,house,Villa General Belgrano,|Argentina|Córdoba|Villa General Belgrano|,Argentina,Córdoba,3832734.0,"-31.979215,-64.555113",-31.979215,-64.555113,...,NaN,NaN,280.0,NaN,NaN,NaN,8.0,NaN,"Estancia ""Las Luciernagas"" es una magnifica pr...",Estancia con costa de arroyo y abundante arboleda
117124,sell,house,Villa General Belgrano,|Argentina|Córdoba|Villa General Belgrano|,Argentina,Córdoba,3832734.0,"-31.978143,-64.55425",-31.978143,-64.554250,...,NaN,NaN,443.0,NaN,NaN,NaN,10.0,NaN,c349- Importante propiedad ubicada sobre Calle...,Importante Propiedad Apta Hotel O Posada
117129,sell,house,Villa General Belgrano,|Argentina|Córdoba|Villa General Belgrano|,Argentina,Córdoba,3832734.0,"-31.989105,-64.561251",-31.989105,-64.561251,...,NaN,NaN,222.0,NaN,NaN,NaN,10.0,NaN,c354- Amplia vivienda en venta con pileta clim...,Casa En Venta Dos Dormitorios Y Departamento -...
117138,sell,house,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,"-31.459209,-64.192731",-31.459209,-64.192731,...,NaN,NaN,145.0,NaN,NaN,NaN,8.0,NaN,Excelente dúplex,Tejas 1
117139,sell,house,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,"-31.448712,-64.173713",-31.448712,-64.173713,...,NaN,NaN,290.0,NaN,NaN,NaN,17.0,NaN,"Amplia casa de 2 plantas, living comedor, esta...",Jardín Espinosa
117140,sell,house,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,"-31.458428,-64.174832",-31.458428,-64.174832,...,NaN,NaN,360.0,NaN,NaN,NaN,17.0,NaN,"Amplia casa de categoría de dos plantas, cuent...",Country Jockey fondo golf
117145,sell,apartment,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,NaN,NaN,NaN,...,61692.04,NaN,NaN,NaN,NaN,NaN,8.0,NaN,VENDO DPTO APTO CREDITO. EL DEPARTAMENTO SE EN...,Departamento en Venta - Sagrada Familia 4229 ...
117146,sell,house,Oncativo,|Argentina|Córdoba|Oncativo|,Argentina,Córdoba,3842621.0,NaN,NaN,NaN,...,89733.88,NaN,160.0,NaN,10000.000000,NaN,8.0,NaN,"Casa de dos dormitorios, cocina comedor, garaj...",Se vende Gran casa en la localidad de oncativo
117153,sell,house,Salta,|Argentina|Salta|Salta|,Argentina,Salta,3838233.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,Corredor Responsable: Pablo Castañeda - C.U.C....,Casa a la Venta 3 Cerritos 2da Rotonda Los Molles
119254,sell,house,Punilla,|Argentina|Córdoba|Punilla|,Argentina,Córdoba,3839996.0,"-31.338518,-64.483202",-31.338518,-64.483202,...,160000.00,NaN,200.0,NaN,800.000000,NaN,9.0,NaN,Corredor Responsable: DANIELA E. CASTRO - CPCP...,CHALET EN VENTA! 3.600mts de Terreno. 3 dorm
119313,sell,house,Santo Tomé,|Argentina|Santa Fe|Santo Tomé|,Argentina,Santa Fe,3835793.0,"-31.658897,-60.779195",-31.658897,-60.779195,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,Corredor Responsable: Ivana Batlle Casas - CCI...,Casa de Categoria en Santo Tome
119332,sell,house,Martínez,|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro...,Argentina,Bs.As. G.B.A. Zona Norte,3430813.0,"-34.483072,-58.486673",-34.483072,-58.486673,...,1863400.00,NaN,259.0,NaN,7194.594595,NaN,9.0,NaN,Corredor Responsable: Jorge Di Pace - C.M.C.P....,Venta Casa con amplio Lote - Bajo Martinez
119355,sell,apartment,Punilla,|Argentina|Córdoba|Punilla|,Argentina,Córdoba,3839996.0,"-31.415698,-64.511077",-31.415698,-64.511077,...,790000.00,NaN,1300.0,NaN,607.692308,NaN,18.0,NaN,Corredor Responsable: Edgardo Tamarit - CPCPI ...,VENTA EXCELENTE COMPLEJO DPTOS - VILLA CARLOS...
119461,sell,house,Martínez,|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro...,Argentina,Bs.As. G.B.A. Zona Norte,3430813.0,"-34.484238,-58.486083",-34.484238,-58.486083,...,1500000.00,NaN,514.0,NaN,2918.287938,NaN,8.0,NaN,Corredor Responsable: Gabriel Sola - CUCICBA 2...,VENTA Importante Casa de 8 Amb c/Piscina- Mart...
119463,sell,house,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,"-31.388016,-64.208061",-31.388016,-64.208061,...,140000.00,NaN,167.0,NaN,838.323353,NaN,9.0,NaN,Corredor Responsable: Carlos Borra - CPCPI 490...,VENTA CASA 3 DORMITORIOS VILLA CABRERA
119479,sell,house,General Roca,|Argentina|Río Negro|General Roca|,Argentina,Río Negro,3855061.0,"-39.09578,-67.092257",-39.095780,-67.092257,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,Corredor Responsable: María José Requena - MP ...,"RE/MAX Revoluciona, vende casa en Villa Regina"
119507,sell,house,Oberá,|Argentina|Misiones|Oberá|,Argentina,Misiones,3430339.0,"-38.416097,-63.616672",-38.416097,-63.616672,...,112372.17,1133.0,NaN,99.181086,NaN,NaN,13.0,NaN,EXCELENTE OPORTUNIDAD DE INVERSIÓN: VENDO TERR...,Casa venta
119508,sell,house,Oberá,|Argentina|Misiones|Oberá|,Argentina,Misiones,3430339.0,"-38.416097,-63.616672",-38.416097,-63.616672,...,112372.17,1133.0,NaN,99.181086,NaN,NaN,9.0,NaN,EXCELENTE OPORTUNIDAD DE INVERSIÓN: VENDO TERR...,Casa venta
119595,sell,house,Balcarce,|Argentina|Buenos Aires Interior|Balcarce|,Argentina,Buenos Aires Interior,3436176.0,"-37.8434916443,-58.2580804772",-37.843492,-58.258080,...,200000.00,404.0,250.0,495.049505,800.000000,NaN,10.0,NaN,"Chalet sobre lote de 13,50x29,92.Ingreso a liv...",Clásico Chalet de categoria
119676,sell,house,San Isidro,|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro...,Argentina,Bs.As. G.B.A. Zona Norte,3428983.0,"-34.468287,-58.50621",-34.468287,-58.506210,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,Corredor Responsable: Juan Carlos Treco - CMCP...,MAGNIFICA PROPIEDAD - CASCO HISTORICO - VISTA RIO
119747,sell,house,Mendiolaza,|Argentina|Córdoba|Mendiolaza|,Argentina,Córdoba,3844424.0,"-31.275967,-64.307873",-31.275967,-64.307873,...,282000.00,NaN,340.0,NaN,829.411765,NaN,12.0,NaN,Corredor Responsable: Matiaz Ruiz Moreno - CPC...,VENDO CASA 4 DORM 3 BAÑOS PILETA en VALLE DEL SOL
119748,sell,house,Mendiolaza,|Argentina|Córdoba|Mendiolaza|,Argentina,Córdoba,3844424.0,"-31.27467,-64.3025",-31.274670,-64.302500,...,126750.00,NaN,134.0,NaN,945.895522,NaN,8.0,NaN,Corredor Responsable: Matiaz Ruiz Moreno - CPC...,"VENDO CASA, MENDIOLAZA Bº VALLE DEL GOLF, OPRT..."
119773,sell,apartment,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,"-31.409098,-64.207063",-31.409098,-64.207063,...,150000.00,NaN,166.0,NaN,903.614458,NaN,8.0,NaN,Corredor Responsable: Carlos Borra - CPCPI 490...,SE VENDE - DEPARTAMENTO DE 3 DORMITORIOS - ALB...
119822,sell,house,Córdoba,|Argentina|Córdoba|Córdoba|,Argentina,Córdoba,3860259.0,NaN,NaN,NaN,...,70000.00,NaN,139.0,NaN,503.597122,NaN,9.0,NaN,Se vende amplia Casa en barrio Los Bou...,Vendo amplia Casa en Barrio Los Boulevares...
119830,sell,house,Mar del Plata,|Argentina|Buenos Aires Costa Atlántica|Mar de...,Argentina,Buenos Aires Costa Atlántica,3430863.0,"-37.9958541,-57.5425943",-37.995854,-57.542594,...,600000.00,336.0,650.0,1785.714286,923.076923,NaN,9.0,NaN,"Casa de 1930, se agrega en 2002 edificio nuevo...",Importante Casona a metros del mar ideal hoste...
119894,sell,house,Punilla,|Argentina|Córdoba|Punilla|,Argentina,Córdoba,3839996.0,"-30.85985,-64.522995",-30.859850,-64.522995,...,295000.00,NaN,135.0,NaN,2185.185185,NaN,10.0,NaN,Corredor Responsable: DANIELA E. CASTRO - CPCP...,Hostel en venta Capilla del Monte
119935,sell,house,Punilla,|Argentina|Córdoba|Punilla|,Argentina,Córdoba,3839996.0,"-31.088003,-64.480702",-31.088003,-64.480702,...,95000.00,NaN,12731.0,NaN,7.462100,1.0,10.0,NaN,Corredor Responsable: Matiaz Ruiz Moreno - CPC...,VENDO CASA LA FALDA 2 DORMITORIOS -APTO CREDITO-
120164,sell,house,Mar del Plata,|Argentina|Buenos Aires Costa Atlántica|Mar de...,Argentina,Buenos Aires Costa Atlántica,3430863.0,NaN,NaN,NaN,...,600000.00,650.0,336.0,923.076923,1785.714286,NaN,9.0,NaN,"Casa de 1930, se agrega en 2002 edificio nuevo...",LA PERLA- IMPORTANTE CASONA IDEAL HOSTEL O REN...

## Como vemos, muchos valores parecerian ser errores al momento de la carga.

Si bien prodriamos eliminar esos datos por considerarlos "outliers", algunos de ellos corresponden a complejos hoteleros, o venta de varias unidades en un mismo edificio.

Nos convendria crear una columna nueva indicando el tipo de propiedad (mas alla de casa/PH/dto)

## Revisar si vale la pena esta parte o no

In [75]:
#df[df['Cantidad_Ambientes']> 7] = np.nan

In [77]:
df.Cantidad_Ambientes.value_counts()

3.0    12567
2.0    12433
4.0     7937
1.0     7377
5.0     3782
6.0     1403
7.0      770
Name: Cantidad_Ambientes, dtype: int64

## Como completamos los valores faltantes?

Una buena idea seria buscar si el dato que no figura en la columna correspondiente, podemos encontrarlo en la columna de Titulo o Descripcion

In [81]:
#Veamos primero como figuran los datos en un caso en particular
df.Descripcion[0:10]

0    2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...
1    Venta de departamento en décimo piso al frente...
2    2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...
3    PH 3 ambientes con patio. Hay 3 deptos en lote...
4    DEPARTAMENTO CON FANTÁSTICA ILUMINACIÓN NATURA...
5    Casa en el perímetro del barrio 338, ubicada e...
6    MUY BUEN PH AL FRENTE CON ENTRADA INDEPENDIENT...
7    EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...
8    EXCELENTE DOS AMBIENTES  ESTRENAR AMPLIO SUPER...
9    MEDNOZA AL 7600A UNA CUADRA DE CALLE MENDOZAWH...
Name: Descripcion, dtype: object

Vemos que hay una buena cantidad de informacion en la descripcion, por lo que vamos a definir una funcion para recorrer el texto y obtener un patron de texto deseado

In [ ]:
##FUNCION PARSER

#Defino una funcion que a partir de un patron, parsee un campo del df

def parser(dataframe,columna, patron):
    lista = []
    largo = len(dataframe)
    for x in range(largo):
        string = dataframe.columna.loc[x]
        match = re.search(patron, string, flags = re.IGNORECASE)
        
        if match:
            lista.append(match.group(1)) #o match.group(1) match[0]
        
    return lista

## En la mayoria de los casos, figura la cantidad de ambientes, seguido de un espacio, seguido de la palabra "Ambientes", "Habitaciones", "Dormitorios", etc

In [90]:
## Veamos entonces la forma de extraer el dato a partir de la descripcion
## Cantidad de ambientes
# Parseo en la descripcion la RegEx que necesito, y le apendo la columna al df
patron = r'(\d+)(\s)(\b(ambientes|ambiente|amb|cuarto|cuartos|habitacion|habitaciones|dormitorio|dormitorios|dorm|hab|has)\b)'

ambientes = df.Descripcion.str.extract(patron, flags= re.IGNORECASE, expand = False)[0].astype(float)

df['Amb_Desc'] = ambientes

In [91]:
#Reemplazo los valores vacios de la columna original con la extraccion de la descripcion.
#Asumimos que todos los valores mayores a 6 no corresponden al dato de queremos
df['Cantidad_Ambientes'] = df['Cantidad_Ambientes'].fillna(df['Amb_Desc'] < 7)

In [61]:
df.Cantidad_Ambientes.value_counts()

True     46065
False    35142
3.0      12567
2.0      12433
4.0       7937
5.0       3782
6.0       1403
7.0        770
8.0        409
10.0       226
9.0        184
11.0        72
12.0        65
13.0        33
14.0        27
15.0        26
17.0        16
16.0        11
20.0        11
22.0         8
18.0         6
21.0         5
19.0         4
25.0         4
30.0         4
32.0         3
23.0         2
31.0         1
24.0         1
27.0         1
28.0         1
29.0         1
Name: Cantidad_Ambientes, dtype: int64

## De la misma manera, nos gustaria completar los casos en donde no contamos con el dato de la superficie

En este caso puede ser un poco mas engorroso, ya que en la descripcion podemos encontrar strings del estilo "a 200 metros del subte", el cual nos arrojaria un falso positivo si seteamos nuestra RegEx para el siguiente grupo de captura:

r'(\d+)(\s)(\b(metros)\b)'

Por eso, usaremos la expresion regular 

r'(\d+)(\s)(\b(m2)\b)'

In [34]:
## Superficie de la propiedad
# Parseo en la descripcion la RegEx que necesito, y le apendo la columna al df
patron = r'(\d+)(\s?)(\b(m2)\b)'

metros = df.Descripcion.str.extract(patron, flags= re.IGNORECASE, expand = False)#[0].astype(float)

#df['Metros_Desc'] =metros

In [35]:
metros

           0    1    2    3
0        NaN  NaN  NaN  NaN
1        NaN  NaN  NaN  NaN
2        NaN  NaN  NaN  NaN
3        NaN  NaN  NaN  NaN
4        NaN  NaN  NaN  NaN
5        NaN  NaN  NaN  NaN
6        106        m2   m2
7        NaN  NaN  NaN  NaN
8        NaN  NaN  NaN  NaN
9        NaN  NaN  NaN  NaN
10       NaN  NaN  NaN  NaN
11       NaN  NaN  NaN  NaN
12       NaN  NaN  NaN  NaN
13       NaN  NaN  NaN  NaN
14       NaN  NaN  NaN  NaN
15       NaN  NaN  NaN  NaN
16       NaN  NaN  NaN  NaN
17       NaN  NaN  NaN  NaN
18        40        m2   m2
19       NaN  NaN  NaN  NaN
20       NaN  NaN  NaN  NaN
21       NaN  NaN  NaN  NaN
22      1000        m2   m2
23       NaN  NaN  NaN  NaN
24       NaN  NaN  NaN  NaN
25       NaN  NaN  NaN  NaN
26       NaN  NaN  NaN  NaN
27       NaN  NaN  NaN  NaN
28       NaN  NaN  NaN  NaN
29       NaN  NaN  NaN  NaN
...      ...  ...  ...  ...
121190   NaN  NaN  NaN  NaN
121191   NaN  NaN  NaN  NaN
121192   NaN  NaN  NaN  NaN
121193   NaN  NaN  NaN  NaN
121194   NaN  NaN  NaN  NaN
121195   NaN  NaN  NaN  NaN
121196   NaN  NaN  NaN  NaN
121197   NaN  NaN  NaN  NaN
121198   NaN  NaN  NaN  NaN
121199   NaN  NaN  NaN  NaN
121200   NaN  NaN  NaN  NaN
121201   NaN  NaN  NaN  NaN
121202   NaN  NaN  NaN  NaN
121203   NaN  NaN  NaN  NaN
121204   NaN  NaN  NaN  NaN
121205   NaN  NaN  NaN  NaN
121206   NaN  NaN  NaN  NaN
121207   210        m2   m2
121208   210        m2   m2
121209   NaN  NaN  NaN  NaN
121210   NaN  NaN  NaN  NaN
121211   NaN  NaN  NaN  NaN
121212   NaN  NaN  NaN  NaN
121213   NaN  NaN  NaN  NaN
121214   NaN  NaN  NaN  NaN
121215   NaN  NaN  NaN  NaN
121216   NaN  NaN  NaN  NaN
121217   NaN  NaN  NaN  NaN
121218   NaN  NaN  NaN  NaN
121219    77        m2   m2

[121220 rows x 4 columns]

In [96]:
#Reemplazo los valores vacios de la columna original con la extraccion de la descripcion.

df['Metros_Totales'] = df['Metros_Totales'].fillna(df['Metros_Desc'])

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121220 entries, 0 to 121219
Data columns (total 23 columns):
Tipo_Operacion        121220 non-null object
Tipo_Propiedad        121220 non-null object
Barrio                121197 non-null object
Ubicacion_Completa    121220 non-null object
Pais                  121220 non-null object
Provincia             121220 non-null object
GeoNames_ID           102503 non-null float64
Latitud_Longitud      69670 non-null object
Latitud               69670 non-null float64
Longitud              69670 non-null float64
Precio                100810 non-null float64
Moneda                100809 non-null object
Precio_ARS            100810 non-null float64
Precio_Dolares        100810 non-null float64
Metros_Totales        81892 non-null float64
Metros_Cubiertos      101313 non-null float64
Precio_m2_Dls         68617 non-null float64
Precio_m2             87658 non-null float64
Pisos                 7899 non-null float64
Cantidad_Ambientes    47390 non-null float64
Expensas              14262 non-null float64
Descripcion           121218 non-null object
Titulo                121220 non-null object
dtypes: float64(13), object(10)
memory usage: 21.3+ MB

In [6]:
df['Descripcion'][1]

'Venta de departamento en décimo piso al frente, a estrenar. Living comedor con ventanales hacia el balcón con pisos de madera. Cocina completa con doble mesada, muebles bajo mesada. Lavadero separado. Toilette.Dormitorio con placard. Segundo dormitorio a dividir. Calefacción por radiadorBaño completo.Balcón corrido. Posibilidad de cochera semicubierta. U$D 20.000                     Aviso publicado por Pixel Inmobiliario (Servicio de Páginas Web para Inmobiliarias).'

In [44]:
## Precio en dolares
# Parseo en la descripcion la RegEx que necesito, y le apendo la columna al df
patron = r'(\b(U$S|$)\b)(\s)(\d+)(\b(\.)\b)(\d+)'

p_dls = df.Descripcion.str.extract(patron, flags= re.IGNORECASE, expand = False)

p_dls

#df['Metros_Desc'] =metros

          0    1    2    3    4    5    6
0       NaN  NaN  NaN  NaN  NaN  NaN  NaN
1       NaN  NaN  NaN  NaN  NaN  NaN  NaN
2       NaN  NaN  NaN  NaN  NaN  NaN  NaN
3       NaN  NaN  NaN  NaN  NaN  NaN  NaN
4       NaN  NaN  NaN  NaN  NaN  NaN  NaN
5       NaN  NaN  NaN  NaN  NaN  NaN  NaN
6       NaN  NaN  NaN  NaN  NaN  NaN  NaN
7       NaN  NaN  NaN  NaN  NaN  NaN  NaN
8       NaN  NaN  NaN  NaN  NaN  NaN  NaN
9       NaN  NaN  NaN  NaN  NaN  NaN  NaN
10      NaN  NaN  NaN  NaN  NaN  NaN  NaN
11      NaN  NaN  NaN  NaN  NaN  NaN  NaN
12      NaN  NaN  NaN  NaN  NaN  NaN  NaN
13      NaN  NaN  NaN  NaN  NaN  NaN  NaN
14      NaN  NaN  NaN  NaN  NaN  NaN  NaN
15      NaN  NaN  NaN  NaN  NaN  NaN  NaN
16      NaN  NaN  NaN  NaN  NaN  NaN  NaN
17      NaN  NaN  NaN  NaN  NaN  NaN  NaN
18      NaN  NaN  NaN  NaN  NaN  NaN  NaN
19      NaN  NaN  NaN  NaN  NaN  NaN  NaN
20      NaN  NaN  NaN  NaN  NaN  NaN  NaN
21      NaN  NaN  NaN  NaN  NaN  NaN  NaN
22      NaN  NaN  NaN  NaN  NaN  NaN  NaN
23      NaN  NaN  NaN  NaN  NaN  NaN  NaN
24      NaN  NaN  NaN  NaN  NaN  NaN  NaN
25      NaN  NaN  NaN  NaN  NaN  NaN  NaN
26      NaN  NaN  NaN  NaN  NaN  NaN  NaN
27      NaN  NaN  NaN  NaN  NaN  NaN  NaN
28      NaN  NaN  NaN  NaN  NaN  NaN  NaN
29      NaN  NaN  NaN  NaN  NaN  NaN  NaN
...     ...  ...  ...  ...  ...  ...  ...
121190  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121191  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121192  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121193  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121194  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121195  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121196  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121197  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121198  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121199  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121200  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121201  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121202  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121203  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121204  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121205  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121206  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121207  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121208  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121209  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121210  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121211  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121212  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121213  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121214  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121215  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121216  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121217  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121218  NaN  NaN  NaN  NaN  NaN  NaN  NaN
121219  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[121220 rows x 7 columns]

In [45]:
REGEX Precio en $

(\$)(\s)(\d+)(\b(\.)\b)(\d+)

SyntaxError: invalid syntax (<ipython-input-45-5fcf61e5785b>, line 1)

In [ ]:
REGEX Precio U$S

(\b(U\$S|\$)\b)(\s)(\d+)(\b(\.)\b)(\d+)

In [ ]:
REGEX metros
(\d+)(\s?)(\w{1})(\d)

(\d+)(\s?)(\w*)(\d{1})

In [42]:
#Importo re para aplicar RegEx
import re

#Defino una funcion que a partir de un patron, parsee un campo del df

def parser (dataframe, columna, patron):
    largo = len(dataframe)
    for x in range(0,largo):
        re.search(patron,dataframe.columna[x])
        return

(\d+)(\s)(\b(ambientes|ambiente|amb)\b)
2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO, REFACCIONADO A NUEVO, PATIO GRANDE, CON LAVADERO, LIVING COMEDOR CON COCINA INTEGRADA, ARTEFACTO DE COCINA, ALACENA, BAÑO COMPLETO, Y DORMITORIO. TODO EN EXCELENTE ESTADO, PARA HABITAR.NO ES APTO CREDITO Aviso publicado por Pixel Inmobiliario (Servicio de Páginas Web para Inmobiliarias).

In [42]:
serie = df.Descripcion.sample(15)

In [40]:
## Superficie de la propiedad
# Parseo en la descripcion la RegEx que necesito, y le apendo la columna al df
patron = r'(\d+)(\b(m2)\b)'

metros = serie.str.extract(patron, flags= re.IGNORECASE, expand = False)#[0].astype(float)

In [41]:
metros

     0    1    2
0  NaN  NaN  NaN
1  NaN  NaN  NaN
2  NaN  NaN  NaN
3  NaN  NaN  NaN
4  NaN  NaN  NaN
5  NaN  NaN  NaN
6  NaN  NaN  NaN
7  NaN  NaN  NaN
8  NaN  NaN  NaN
9  NaN  NaN  NaN

In [43]:
serie.to_csv()

'85691,"EXCLUSIVA UNIDAD DE 1 AMBIENTE A ESTRENAR, APTO PROFESIONALEXCELENTE UBICACIÓNDETALLES DE TERMINACIÓN Y AMENITIES- Piscina climatizada- SUM - GYM - Juegos para niños- Parrillas - Seguridad 24hsBBU2966 AP193053"\n111613,El precio se compone de un monto en U$S que corresponde a la parte proporcional del Terreno y un monto en $ que corresponde a la Construccion. Aprox. el 60% dividido en 36 cuotas y el saldo en la posesión.  Todo se ajusta por el Indice CACBBU2970 AP192566\n102575,"DEL CAMPO VENDE: Excelente Departamento en inmejorable ubicacion. Living comedor en L con salida a balcon. Vista abierta . Dos dormitorios comodos, uno en suitte, ambos con salida a balcon corrido con vista abierta. Dos baños completos. Cocina y lavadero."\n2816,"SE VENDE!!! EXCELENTE OPORTUNIDAD PARA INVERSIONISTAS!!Tres departamentos de 2 ambientes, muy buena ubicación!!! Se venden juntos o separados."\n72714,"Casa con tres dormitorios, baño, cocina, living-comedor, entrada vehicular y patio. Medidas del lote: 12.77 x 17.38"\n58668,"Cómodo departamento de 3 ambientes a una cuadra del mar, living-comedor luminoso con salida a la terraza, toilette, 1 dormitorio y un escritorio o segundo dormitorio, cocina, calefacción por tiro balanceado y gran terraza de 100 m2 con parrilla y deposito."\n4942,"ESTADO DE ISRAEL 4272 - CERCA DE TODOEdificio en construcciónAnticipo en dólares y 36 cuotas en pesos actualizadas por C.A.CAmplio 3 ambientes a estrenar con gran balcón al contrafrente. Cómodo dormitorio en Suite con vestidor. La unidad cuenta con 2 baños completos, cocina incorporada con desayunador y cocina a gas. Lavadero independiente. Instalación preparada para AA frio/calor. Muy luminoso! Hermoso diseño y confort. Excelente ubicación sobre Avenida Estado de Israel, a mts de Av. Córdoba y Av. Corrientes. Gran variedad de medios de transporte.Sup total: 75 m2. Para vivir, trabajar, invertir!Unidades disponibles de: 1 ambiente divisible con balcón // 2 y 3 ambientes con baño en suite, toilette y balcón.Amenities: SUM en el último piso, Parrilla, Laundry, Terraza.Cocheras disponibles desde u$s 23.000.-Entrega estimada: agosto 2019.- Obtené beneficios asociándote gratis al Club Openprop:  - Consultanos al .OPENPROP Desarrollos Inmobiliarios"\n50979,"Corredor Responsable: Hector Garaygorta - III Cj. Río Negro Mat. N° 214Contacto: Franca Svaluto - MLS ID # 211031-156Departamento en venta en Bariloche. Bº Belgrano. Propiedad con vista panorámica al lago Nahuel Huapi y Cordillera. Ubicado en calle Tucumán en el 4to piso de un edificio de categoría, el departamento posee  88 m2. Se ingresa a un amplio pasillo, a la derecha cocina con comedor dividido por una mesada. Luego un escritorio o dormitorio y un baño completo. Hacia atrás tenemos 2 dormitorios amplios con otro baño completo. Lavadero empotrado como armario. Muy buena carpintería. Piso de madera flotante, cerámicos y alfombra. Todos los servicios. Calefacción por losa radiante. Baulera muy amplia. Cochera bien ubicada. "\n48680,"Corredor Responsable: Lucrecia Saulle - CSI 5520Contacto: Diego Valdez - MLS ID # 341160-107Casa estilo Bariloche (de troncos) muy Bonita, sobre muy buen lote en esquina de 561 m2  Excelente estado de mantenimiento  Planta Baja - Gran Living en doble altura con hogar - Dormitorio con placards y baño completo. Aire Acondicionado - Cocina con amplio comedor diario  Planta Alta - 3 Dormitorios  - Baño Completo - Escritorio  Exterior - Gran Jardín con riego por aspersión (automático) - Muy buen quincho con parrilla - Baño - Piscina de 7m x 3,5 m - Canil para perros - Garage semicubierto para 2 autos  Bomba sumergible a 3° napa Bomba presurizadora "\n50854,AMPLIO DEPARTAMENTO DE DOS AMBIENTES con HABITACION y BAÑO DE SERVICO. BALCON EXTERNO SOBRE AV. COLON. VISTA A PLAZA COLON. MUY BUEN ESTADO DE CONSERVACION.\n75512,Departamento 2 ambientes con balcón terraza con parrilla7mo pìsoAl frente living comedor con balcón terraza con parrillaCocina semiintegrada Dormitorio con amplios placares y baño completo54 m2Financia hasta 36 cuotas!!CONSULTEEntrega en Enero 2018(codigo_referencia)\n29948,"CASA BLANCA - VENTA  - DEPARTAMENTO - 1 DORMITORIO  - PARQUE SAN FRANCISCO - CÓRDOBA* UBICACION:  A pocos metros del centro comercial Dinosaurio mall y próximo a la Avda. Fuerza Aérea* AMENITIES: Piscina y solarium.* SEGURIDAD: Monitoreo por cámara las 24 hs.* COCHERAS: Sí, en subsuelo.* COCINA: Separada, con amoblamiento bajo mesada y espacio para lavarropas. Mesada de granito con bacha de 1º marca.* BAÑOS: Con bañera y artefactos sanitarios de primera calidad.* DORMITORIO: Amplios con placares.* AMENITIES: Piscina y solarium. Sector de parrillas en patio comun y sanitarios para uso de la piscina. POR OPCIONES SIMILARES  -  - INMOBILIARIA CUATRORAICES"\n76916,"-- Casa desarrollada en tres plantas con jardin y piscina-- Planta baja-= JARDIN al frente con rejas= GARAGE para dos autos, 2,9 X 10,5 porton levadizo manual de madera, pisoss cemento= Hall 1,5 x 4,4 piso ceramico= LIVING 3,6 x 6-+ 3,5 x 6,1 en desnivel alfombrado, con puerta ventana al patio= COCINA 2,7 X3,2 con altos y bajos mesada, piso ceramico= COMEDOR 4,3 X 3 = Distribuidor 1,4 x 3,3 con placard acceso a planta alta= HABITACION 3,5 X 3 = Toillete 3,2 x 1,7 piso ceramico= Lavadero 1,5 x 2,90 piso ceramico, termotanque= PATIO 1,6 X 4,60 descubierta, pisos ceramico, = Jardin libre con piscina= Quincho 9 x 5 con parrilla con gas, toillete 1,9 x 2-- Planta alta-= Baño 3,5 x 3 completo , piso ceramico= Distribuidor 3,15 x 4,2 = DORMITORIO 3,45 X 4,8 piso ceramico con balcon con altillo= DORMITORIO 4,05 X 3,6 con balcon= Habitacion 3,3 x 2,3 -- En planta 2 piso = Playroom y escritorio= Habitacion 4 x 4, 6= Escalera 4,7 x 1,5 + paso 2 x 1,8 --- 2 tanques de agua - calefaccion por tiro balanceado - aire acondicionado----- consulte ---Las ofertas descriptas estan sujetas a disponibilidad y la informacion dada podra contener imprecisiones tecnicas o errores tipograficos."\n73039,".......ficha en construccion......3 dtos por piso, 2 ascensores=LIVING 2,70 X 3,40 piso ceramico, mas 3,75 x 3,95-=COCINA 2,55 x 3,2 altos y bajos mesada, piso ceramico, calefon= BAÑO 1,55 x 1,95-=lavadero 1 x 1,65 cubierto-Las ofertas descriptas estan sujetas a disponibilidad y la informacion dada podra contener imprecisiones tecnicas o errores tipograficos."\n119552,"Venta de Departamento 1 AMBIENTE en Villa Ballester, General San MartínMONO AMBIENTE A ESTRENAR , BAÑO COMPLETO , BALCÓN AL FRENTE. CONSULTE POR FINANCIACIÓN DIRECTA.PARA MAS INFORMACIÓN COMUNÍQUESE CON NOSOTROS AL  /  DE LUN A VIE DE 9.30 A 12.30 HS / 15.30 A 19.30 HS Y SAB. DE 9.30 A 13HS O INGRESE EN NUESTRA WEB:  TAMBIÉN PODES ENCONTRARNOS EN: , TWITTER/, GOOGLE+ Y LINKEDIN. -  - ROCCHIO PROPIEDADES"\n'

In [27]:
#Defino una funcion que a partir de un patron, parsee un campo del df

def parser(dataframe,columna, patron):
    lista = []
    largo = len(dataframe)
    for x in range(0,largo):
        string = dataframe.columna.loc[x]
        match = re.search(patron, string, flags = re.IGNORECASE)
        
        if match:
            lista.append(match[0]) #o match.group(1)
        
    return lista

In [24]:
serie.reset_index(drop=True, inplace=True)

In [25]:
df.Descripcion.iloc[0]

'2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO, REFACCIONADO A NUEVO, PATIO GRANDE, CON LAVADERO, LIVING COMEDOR CON COCINA INTEGRADA, ARTEFACTO DE COCINA, ALACENA, BAÑO COMPLETO, Y DORMITORIO. TODO EN EXCELENTE ESTADO, PARA HABITAR.NO ES APTO CREDITO Aviso publicado por Pixel Inmobiliario (Servicio de Páginas Web para Inmobiliarias).'

In [28]:
parser(serie,r'(\d+)(\s)(\b(ambientes|ambiente|amb|cuarto|cuartos|habitacion|habitaciones|dormitorio|dormitorios)\b)')

['3 ambientes',
 '3 dormitorios',
 '1 ambiente',
 '2 dormitorios',
 '2 AMBIENTES',
 '3 dormitorios']

In [ ]:
pattern = r'(\d+)(\s)(\b(ambientes|ambiente|amb)\b)'
#r'(\d+)(\s)(\b(AMB|amb|Amb|AMBIENTES|ambientes|Ambientes|HAB|hab|habitaciones|Habitaciones|cuartos|Cuartos|Dormitorios|dormitorios|ambiente|habitacion)\b)'


string = df.Descripcion[0]

f = re.search(pattern,string, flags = re.IGNORECASE)

print(pattern)
print(string)

In [96]:
parser(df,df.Descripcion,r'(\d+)(\s)(\b(ambientes|ambiente|amb|cuarto|cuartos|habitacion|habitaciones|dormitorio|dormitorios)\b)')

'2 AMBIENTES'

In [13]:
print(f[0])

2 AMBIENTES

In [ ]:
# Hago un value_count de las columnas que me interesan ver
for c in ['Tipo_Propiedad', 'Provincia']:
        print ('-----{}-----'.format(c))
        print (df[c].value_counts())
        print('')